made some changes on task5
MrQalati/14-August pull request #5
Opened 2023-08-17 13:57 UTC by MrQalati

2023-08-17 14:13 UTC, EddTheDuck requested changes
Nearly there! Just some changes needed before merging, see comments.

2023-08-17 14:13 UTC, EddTheDuck commented on __tests__/app.test.js
> +            articles.forEach((article) => {
When asserting inside a forEach you need to check the length of the array first to ensure no false positives.

2023-08-17 14:13 UTC, EddTheDuck commented on __tests__/app.test.js
> +              expect(article).not.toHaveProperty('body');
I can see where you are coming from with this line of testing however we know a lot more about the data we should be getting so therefore our assertions can be much more specific. Have a look at .objectcontaining or toMatchObject matchers to implement this

2023-08-17 14:13 UTC, EddTheDuck commented on __tests__/app.test.js
> +            });
You already tested for this above so this test is kinda redundant

2023-08-17 14:13 UTC, EddTheDuck commented on __tests__/app.test.js
> +              expect(currentArticleDate).toBeGreaterThanOrEqual(nextArticleDate);
Reformat this using jest-sorted (https://www.npmjs.com/package/jest-sorted) - makes this sort of testing easier and also easier to read.

2023-08-17 14:13 UTC, EddTheDuck commented on __tests__/app.test.js
> +      });
this test shouldn't be in the describe block for /api/articles as it is a generic error handling test for any time an endpoint doesn't exist therefore should be seperate.

2023-08-17 14:13 UTC, EddTheDuck commented on controllers/new-articles-controllers.js
> +          return {
This should all be done in the query to the DB. When possible we shouldn't be fetching all the data and then manipulating it, this should be done server side.

2023-08-17 14:13 UTC, EddTheDuck commented on models/new-articles-models.js
> +      FROM articles
Instead of fetching everything from the articles, why not just fetch only what you need? e.g not the body :D

2023-08-17 14:13 UTC, EddTheDuck commented on models/new-articles-models.js
> +        console.log('Fetched data:', result.rows);
remove console.logs before submitting PR

2023-08-17 15:50 UTC, nc-poppy-m requested changes
Well done for editing the tests, however Edd has left you feedback for other parts of your work like your models and controllers which it doesn't look like you've actioned, so please have a look and fix that. Then submit another PR tomorrow morning

2023-08-18 08:35 UTC, Augs0 approved these changes
Looks good 👍  you're okay to merge

2023-08-18 08:37 UTC, merged